# Generated by Django 5.1.2 on 2024-10-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=15)),
                ('foto_perfil', models.ImageField(upload_to='fotos_perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('nota', models.FloatField()),
                ('retroalimentacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_academica.usuario')),
            ],
            bases=('gestion_academica.usuario',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_academica.usuario')),
                ('historial_academico', models.JSONField()),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('creditos_acumulados', models.IntegerField()),
            ],
            bases=('gestion_academica.usuario',),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('documentos', models.FileField(upload_to='documentos_cursos/')),
                ('estudiantes', models.ManyToManyField(related_name='cursos', to='gestion_academica.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_academica.usuario')),
                ('cursos_asignados', models.ManyToManyField(related_name='profesores_asignados', to='gestion_academica.curso')),
            ],
            bases=('gestion_academica.usuario',),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_impartidos', to='gestion_academica.profesor'),
        ),
    ]
